basePath: /api/v1
definitions:
  dto.AuthURLResponse:
    properties:
      auth_url:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: A RESTful API built with Go and Fiber
  title: Pitstop API
  version: "1.0"
paths:
  /auth/google:
    get:
      consumes:
      - application/json
      description: Get Google OAuth authorization URL
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.AuthURLResponse'
      summary: Initiate Google OAuth
      tags:
      - auth
  /auth/google/callback:
    get:
      consumes:
      - application/json
      description: Exchange authorization code for access token
      parameters:
      - description: Authorization code
        in: query
        name: code
        required: true
        type: string
      - description: CSRF state token
        in: query
        name: state
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Handle Google OAuth callback
      tags:
      - auth
swagger: "2.0"
